# Generated by Django 5.1.6 on 2025-05-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile',
        ),
    ]
