# Generated by Django 5.1.6 on 2025-05-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_shippingaddress_shipping_address2_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address1',
            new_name='shipping_address',
        ),
    ]
